
package UI;
import Modelo.Contacto;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane; // Para mostrar mensajes
/**
 *
 * @author sebas
 */
public class FormularioContacto extends javax.swing.JDialog {
    private Contacto contacto; // Almacena el contacto que se está agregando o editando
    private boolean esEdicion; // Indica si el formulario está en modo edición

    /**
     * Constructor para agregar un nuevo contacto.
     * @param parent El frame padre.
     * @param modal Si el diálogo debe ser modal.
     */
    public FormularioContacto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent); // Centra el formulario respecto a la ventana principal
        this.esEdicion = false; // Modo agregar
        this.contacto = new Contacto(); // Se crea un nuevo contacto vacío
        btnAceptarContacto.setText("Agregar"); // Texto del botón para agregar
        setTitle("Agregar Contacto"); // Título del diálogo
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Si el usuario cierra con la 'X', se considera una cancelación
                boolean accepted = false;
                // En modo edición, también anulamos el contacto para que VentanaPrincipal
                contacto = null;
            }
        });
    }

    /**
     * Constructor para editar un contacto existente.
     * @param parent El frame padre.
     * @param modal Si el diálogo debe ser modal.
     * @param contactoAEditar El objeto Contacto a editar.
     */
    public FormularioContacto(java.awt.Frame parent, boolean modal, Contacto contactoAEditar) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent); // Centra el formulario respecto a la ventana principal
        this.esEdicion = true; // Modo edición
        this.contacto = contactoAEditar; // Se referencia el contacto existente
        cargarDatosContacto(); // Carga los datos del contacto en los campos del formulario
        setTitle("Editar Contacto"); // Título del diálogo
    }

    private void cargarDatosContacto() {
        if (contacto != null) {
            txtNombre.setText(contacto.getNombres());
            txtApellidos.setText(contacto.getApellidos());
            txtTelefono.setText(contacto.getTelefono());
            txtEmail.setText(contacto.getEmail());
        }
    }
    public Contacto getContacto() { // ¡Importante: este método debe ser público!
    return contacto;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAceptarContacto = new javax.swing.JButton();
        btnCancelarContacto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Nombre");

        jLabel7.setText("Apellidos");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Email");

        btnAceptarContacto.setText("Aceptar");
        btnAceptarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarContactoActionPerformed(evt);
            }
        });

        btnCancelarContacto.setText("Cancelar");
        btnCancelarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptarContacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarContacto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtApellidos)
                            .addComponent(txtTelefono)
                            .addComponent(txtEmail))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarContacto)
                    .addComponent(btnCancelarContacto))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarContactoActionPerformed
// Validación básica: Nombre, Apellido y Teléfono son obligatorios
        if (txtNombre.getText().trim().isEmpty() ||
            txtApellidos.getText().trim().isEmpty() ||
            txtTelefono.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre, Apellido y Teléfono son campos obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Asigna los valores de los campos de texto a la instancia de Contacto
        contacto.setNombres(txtNombre.getText().trim());
        contacto.setApellidos(txtApellidos.getText().trim());
        contacto.setTelefono(txtTelefono.getText().trim());
        contacto.setEmail(txtEmail.getText().trim());

        dispose(); // Cierra el JDialog
    }//GEN-LAST:event_btnAceptarContactoActionPerformed

    private void btnCancelarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarContactoActionPerformed
        this.contacto = null;
        dispose(); // Cierra el JDialog       
    }//GEN-LAST:event_btnCancelarContactoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioContacto dialog = new FormularioContacto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarContacto;
    private javax.swing.JButton btnCancelarContacto;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
